AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - '**/Gemfile'

Style/FileName:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/MethodLength:
   Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

# Metrics/LineLength:
#   Max: 120
#
# Metrics/BlockLength:
#   Enabled: false
#
# Style/StringLiterals:
#   Enabled: true
