source "https://rubygems.org"

gem "elasticsearch", "~> 0.4.3"
gem "twitter",       "~> 5.3.0"

gem "colored",       "~> 1.2"

# https://github.com/elasticsearch/elasticsearch-ruby/blob/master/elasticsearch-api/README.md#using-hash-wrappers

# gem "hashie",        "~> 2.0.5"

# gem "curb",          "~> 0.8.5"
