require 'rubygems'
require 'bundler'
Bundler.setup

require 'rake'
require 'couchrest'
require 'rack/mime'
require 'yajl/http_stream'

Database = CouchRest.database!('http://127.0.0.1:4000/couchapp_06')


desc "Upload Led Zeppelin data"
task :default => [:populate] do
  puts "-"*80
  puts "Uploaded application data into database, please check:",
       " * http://localhost:4000/couchapp_06/_design/app/_show/info/led-zeppelin-ii",
       " * http://localhost:4000/couchapp_06/_design/app/_show/info/led-zeppelin-iii"
end


desc "Create documents with attachments in couchapp_06 database"
task :populate do

  Database.recreate!

  assets_folder = Pathname.new('led_zeppelin')

  # doc = {
  #   '_id'   => '_design/assets',
  #   '_attachments' => {},
  # }

  # puts "* Reading assets in '#{assets_folder}':"
  # FileList.new("#{assets_folder}/**/*.*").each do |source|
  #   attachment = source.gsub(Regexp.new("^#{assets_folder}/(.*)$"), '\1')
  #   puts "  - #{attachment}"
  #   doc['_attachments'][attachment] = {
  #     'content_type' => Rack::Mime.mime_type( File.extname(assets_folder.join(attachment)) ),
  #     'data' => File.read(assets_folder.join(attachment))
  #   }
  # end

  # rev = Database.get('_design/assets')['_rev'] rescue nil
  # doc.update( {'_rev' => rev} ) if rev

  # p doc['_attachments'].keys
  # Database.save_doc(doc)

end
