#!/usr/bin/env ruby

# this script requires ruby 1.9.2

# try:
# 
#   ./markov young
#   ./markov young
#   ./markov words
#   ./markov words

require 'couchrest'

couch = CouchRest.new("http://localhost:4000")
Database = couch.database('gutenberg')

@word_memoizer = {}

def probable_follower_for(word)
  # http://localhost:4000/gutenberg/_design/wc/_view/markov?startkey=["young",null]&["young",{}]&group_level=2
  @word_memoizer[word] ||= Database.view('wc/markov', :startkey=>[word,nil], :endkey=>[word,{}], :group_level=>2)
  row =  @word_memoizer[word]['rows'].sample # get random row
  #row ? row['key'][1] : nil
  row['key'][1]
end

word = ARGV[0]

max_words = 44
counter = 0
while word && counter < max_words
  print word, " "
  word = probable_follower_for(word)
  counter += 1
end
print "\n"
