#! /usr/bin/env ruby

# documentation
#   http://trollop.rubyforge.org/
# ARGF: Automatically Read from Files or Standard Input
#

require 'bundler/setup'

require 'trollop'
require 'oj'
require 'mongo'

# handle options

options = Trollop::options do
  version "json2mongo 0.0.1 (c) 2013 Wlodek Bzyl"
  banner <<-EOS
Import JSON data into MongoDB.
When importing JSON documents, each document must be a separate line of the input file.

Example:
  json2mongo --host 127.0.0.1 --db test --collection docs < mydocfile.json

Options:
EOS

  opt :db,         "database to use", type: :string, default: "test"
  opt :collection, "collection to use", type: :string # default nil
  opt :host,       "mongo host to connect to",  type: :string, default: "127.0.0.1"
  opt :port,       "server port", type: :string, default: "27017"
  opt :drop,       "drop collection first" # flag; default false

  opt :batch,      "batch size for bulk inserts", type: :integer, default: 4
  opt :upsert,     "insert or update objects that already exist" # flag; default false
end

Trollop::die :collection, "must be given" unless options[:collection]

# transform hashified JSON

def transform(hash)
  # hash['city'].capitalize!
  city = hash.delete('city')
  hash['city'] = city.split(" ").map(&:capitalize!).join(" ")
  puts "#{hash['city']}"
  hash
end

# connect to MongoDB

include Mongo

# write concern: https://github.com/mongodb/mongo-ruby-driver/wiki/Write-Concern
  db = MongoClient.new(options[:host], options[:port], w: 1, wtimeout: 200, j: true).db(options[:db])
coll = db.collection(options[:collection])

coll.drop if options[:drop]

# puts "ARGF.filename: #{ARGF.filename}"

batch = []
ARGF.each_line do |line|
  batch << transform(Oj.load(line))

  if ARGF.eof? || ARGF.lineno % options[:batch] == 0
    coll.insert(batch)
    batch = []
  end
end
