#! /bin/env ruby

def to_tsv(file_name, title, author, pre, post)
  lines = IO.readlines(file_name)
  text = lines[pre...-post].join()
  paragraphs = text.split("\n\n")
  paragraphs.each do |p|
    puts "#{title}\t#{author}\t#{p.gsub(/\s+/,' ')}"
  end
end

puts "title\tauthor\tp" # headerline

to_tsv("the-idiot.txt", "The Idiot", "Dostoyevsky, Fyodor", 47, 368)
to_tsv("the-man-who-knew-too-much.txt", "The Man Who Knew Too Much", "Chesterton, Gilbert K", 51, 368)

__END__
Example:

  head -47  the-idiot.txt
  tail -368 the-idiot.txt

the-idiot.txt
Title: Title: The Idiot
Author: Fyodor Dostoyevsky

the-man-who-knew-too-much.txt
Title: The Man Who Knew Too Much
Author: G.K. Chesterton

the-sign-of-the-four.txt
Title: The Sign of the Four
Author: Arthur Conan Doyle

war-and-peace.txt
Title: War and Peace
Author: Leo Tolstoy
